/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c DemoIfAdaptor -a demoifadaptor.h:demoifadaptor.cpp com.nokia.Demo.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "demoifadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DemoIfAdaptor
 */

DemoIfAdaptor::DemoIfAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DemoIfAdaptor::~DemoIfAdaptor()
{
    // destructor
}

void DemoIfAdaptor::SayBye()
{
    // handle method call com.nokia.Demo.SayBye
    QMetaObject::invokeMethod(parent(), "SayBye");
}

void DemoIfAdaptor::SayHello(const QString &name, const QVariantMap &customdata)
{
    // handle method call com.nokia.Demo.SayHello
    QMetaObject::invokeMethod(parent(), "SayHello", Q_ARG(QString, name), Q_ARG(QVariantMap, customdata));
}

